Move to LXD snap
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

diff --git a/debian/lxd.preinst b/debian/lxd.preinst
--- a/debian/lxd.preinst
+++ b/debian/lxd.preinst
@@ -1,63 +1,105 @@
 #!/bin/sh
 set -e
 
-add_groups()
-{
-    if ! getent passwd lxd >/dev/null; then
-        adduser --system lxd --home /var/lib/lxd/ --shell /bin/false
-
-        # UID allocation
-        NEXT_UID=100000
-        while read line; do
-            OLD_IFS=$IFS
-            IFS=":"
-            set -- $line
-            IFS=$OLD_IFS
-
-            [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] && continue
-
-            LAST=$(($2+$3))
-            [ "$LAST" -gt "$NEXT_UID" ] && NEXT_UID=$LAST
-        done < /etc/subuid
-        usermod --add-subuids ${NEXT_UID}-$(($NEXT_UID+65535)) lxd
-        usermod --add-subuids ${NEXT_UID}-$(($NEXT_UID+65535)) root
-
-        # GID allocation
-        NEXT_GID=100000
-        while read line; do
-            OLD_IFS=$IFS
-            IFS=":"
-            set -- $line
-            IFS=$OLD_IFS
-
-            [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] && continue
-
-            LAST=$(($2+$3))
-            [ "$LAST" -gt "$NEXT_GID" ] && NEXT_GID=$LAST
-        done < /etc/subgid
-        usermod --add-subgids ${NEXT_GID}-$(($NEXT_GID+65535)) lxd
-        usermod --add-subgids ${NEXT_GID}-$(($NEXT_GID+65535)) root
-    fi
-
-    if ! getent group lxd >/dev/null; then
-        addgroup --system lxd
-    fi
-
-    # Add each admin user to the lxd group - for systems installed
-    # before precise
-    for u in $(getent group admin | sed -e "s/^.*://" -e "s/,/ /g"); do
-        adduser "$u" lxd >/dev/null || true
-    done
-
-    # Add each sudo user to the lxd group
-    for u in $(getent group sudo | sed -e "s/^.*://" -e "s/,/ /g"); do
-        adduser "$u" lxd >/dev/null || true
-    done
-}
-
 case "$1" in
     install|upgrade)
-        add_groups
+        . /usr/share/debconf/confmodule
+
+        if [ -e "/var/lib/lxd" ]; then
+            echo "=> Migrating to the LXD snap"
+
+            # Warn about downtime
+            db_input high lxd/snap-upgrade-warning || true
+            db_go
+
+            # Check store connectivity
+            echo "==> Checking connectivity with the snap store"
+            COUNT=0
+            while :; do
+                snap info lxd >/dev/null 2>&1 && break
+
+                db_fset lxd/snap-no-connectivity seen false
+                if ! db_input critical lxd/snap-no-connectivity; then
+                    if [ "${COUNT}" = "0" ]; then
+                        echo "===> Unable to contact the store, trying every minute for the next 30 minutes"
+                    elif [ "${COUNT}" = "10" ]; then
+                        echo "===> Still unable to contact the store, trying for another 20 minutes"
+                    elif [ "${COUNT}" = "20" ]; then
+                        echo "===> Still unable to contact the store, trying for another 10 minutes"
+                    elif [ "${COUNT}" = "30" ]; then
+                        echo "===> Still unable to contact the store, aborting"
+                        exit 1
+                    fi
+
+                    sleep 1m
+                else
+                    if [ "${COUNT}" = "0" ]; then
+                        echo "===> Unable to contact the store"
+                    fi
+                fi
+
+                db_go
+                COUNT=$((COUNT+1))
+            done
+
+            # Set the default track
+            db_get lxd/snap-track
+            if [ -z "${RET}" ]; then
+                if [ -e "/etc/os-release" ] && grep -q " LTS " /etc/os-release; then
+                    db_set lxd/snap-track "3.0"
+                fi
+
+                db_fset lxd/snap-track seen false
+            fi
+
+            # Prompt about track
+            db_input high lxd/snap-track || true
+            db_go
+
+            # Get the track
+            db_get lxd/snap-track
+            track=${RET}
+
+            # Workaround for broken systems
+            mkdir -p /lib/modules
+
+            # Extract the OS release
+            RELEASE="18.10"
+            if [ -e "/etc/os-release" ]; then
+                RELEASE=$(. /etc/os-release && echo "${VERSION_ID}")
+            fi
+
+            # Install the snap
+            echo "==> Installing the LXD snap from the ${track} track for ubuntu-${RELEASE}"
+            if [ "${track}" = "latest" ]; then
+                snap install lxd --channel="stable/ubuntu-${RELEASE}"
+            else
+                snap install lxd --channel="${track}/stable/ubuntu-${RELEASE}"
+            fi
+
+            if [ -e "/var/lib/lxd/server.crt" ]; then
+                echo "==> Waiting for LXD to be online (10min timeout)"
+                /snap/bin/lxd waitready --timeout=600
+
+                echo "==> Running migration from Deb to Snap"
+                export LXD_PREINST=1
+                /snap/bin/lxd.migrate --yes
+            else
+                echo "==> LXD appears unconfigured/unused, skipping migration"
+            fi
+
+            echo "==> Cleaning up leftovers"
+            deb-systemd-invoke stop lxd.socket lxd.service lxd-containers.service || true
+            deb-systemd-invoke disable lxd.socket lxd.service lxd-containers.service || true
+            rm -rf --one-file-system /etc/dnsmasq.d-available/lxd
+            rm -rf --one-file-system /etc/init.d/lxd
+            rm -rf --one-file-system /etc/logrotate.d/lxd
+            rm -rf --one-file-system /etc/sysctl.d/10-lxd-inotify.conf
+            rm -rf --one-file-system /var/lib/lxd
+            rm -rf --one-file-system /var/log/lxd
+
+            echo "=> Migration complete"
+        fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
